"""add idx to m2m struct_adm positions

Revision ID: 57675e7ca4c2
Revises: 96d88e78c8a7
Create Date: 2024-09-03 14:40:22.330419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57675e7ca4c2'
down_revision: Union[str, None] = '96d88e78c8a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('idx_unique_struct_adm_position', 'struct_adm_position', ['struct_adm_id', 'position_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('idx_unique_struct_adm_position', 'struct_adm_position', type_='unique')
    # ### end Alembic commands ###
