"""delete

Revision ID: 96d88e78c8a7
Revises: d1d765bf812b
Create Date: 2024-09-02 16:47:45.492493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96d88e78c8a7'
down_revision: Union[str, None] = 'd1d765bf812b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_struct_adm_parent_id_struct_adm', 'struct_adm', type_='foreignkey')
    op.create_foreign_key(op.f('fk_struct_adm_parent_id_struct_adm'), 'struct_adm', 'struct_adm', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_struct_adm_parent_id_struct_adm'), 'struct_adm', type_='foreignkey')
    op.create_foreign_key('fk_struct_adm_parent_id_struct_adm', 'struct_adm', 'struct_adm', ['parent_id'], ['id'])
    # ### end Alembic commands ###
